# Generated by Django 2.1.3 on 2018-11-29 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.TextField(null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REJECTED', 'Rejected'), ('TO_AUDIT', 'To_Audit'), ('TO_APPROVE', 'To_Approve'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10)),
                ('rejected_at', models.CharField(choices=[('AUDIT', 'AUDIT'), ('APPROVAL', 'APPROVAL')], max_length=8, null=True)),
                ('department', models.CharField(choices=[('CA', 'Clothing and Apparel'), ('HD', 'Home and Decors'), ('CS', 'Construction Supplies')], default='CA', max_length=2)),
                ('week', models.CharField(max_length=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(max_length=11, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(default=0)),
                ('department', models.CharField(choices=[('CA', 'Clothing and Apparel'), ('HD', 'Home and Decors'), ('CS', 'Construction Supplies')], default='CA', max_length=2)),
                ('stocks', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN'), ('auditor', 'AUDITOR'), ('manager', 'MANAGER')], default='user', max_length=7)),
                ('department', models.CharField(choices=[('CA', 'Clothing and Apparel'), ('HD', 'Home and Decors'), ('CS', 'Construction Supplies')], default='CA', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
